url: "https://rosewills.github.io"			# Hostname & protocol of site (e.g. http://example.com)
baseurl: "/a-study-in-gravity"							# Subpath of site (e.g. /blog)
title: "A Study in Gravity"				# Name of site (e.g. ACME Corp.)
description: "On carrying loss as a student."
email: rmvwills@gmail.com
name: Rose Wills


cover: ""
acover: ""	# /assets/art/windowsill.png
bcover: ""
logo:
future: false

permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20

# # Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

exclude:							# Ignore these directories when generating the site
  - "/vendor/"
  - "/template/"
  - ".obsidian/"
  - "ofiles/"
